##
##  Container to model Active Directory
##

services:
  ldap:
    build: .
    image: ldap:demo
    restart: always
    container_name: ldap
    networks:
      - ldap-network
    environment:
      - TERM=xterm
      - SLAPD_PASSWORD=secret
      - SLAPD_DOMAIN=example.com
      - SLAPD_ADDITIONAL_MODULES=memberof
    ports:
      - "9489:389"
    volumes:
      - ./ldif_prepopulate:/etc/ldap.dist/prepopulate
    healthcheck:
      test: ["CMD", "ldapsearch", "-x", "-H", "ldap://localhost:389", "-b", "dc=example,dc=com", "-s", "sub", "(CN=usertwo)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  ldap-network:
    external: true
